name: types_for_auth
description: Types used during authentication and authorizion.
version: 0.0.0-a1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  enspyr_lints: ^0.0.0-a1
  test: ^1.21.0
